// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
void ui_event_scrMain(lv_event_t * e);
lv_obj_t * ui_scrMain;
void ui_event_pnlMain(lv_event_t * e);
lv_obj_t * ui_pnlMain;
lv_obj_t * ui_Image1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;


// SCREEN: ui_scrSettings
void ui_scrSettings_screen_init(void);
void ui_event_scrSettings(lv_event_t * e);
lv_obj_t * ui_scrSettings;
void ui_event_Panel1(lv_event_t * e);
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label1;
void ui_event_sldVolume(lv_event_t * e);
lv_obj_t * ui_sldVolume;
void ui_event_sldBrightness(lv_event_t * e);
lv_obj_t * ui_sldBrightness;
lv_obj_t * ui_Label2;
void ui_event_ButtonOK(lv_event_t * e);
lv_obj_t * ui_ButtonOK;
lv_obj_t * ui_Label4;


// SCREEN: ui_scrRadio
void ui_scrRadio_screen_init(void);
void ui_event_scrRadio(lv_event_t * e);
lv_obj_t * ui_scrRadio;
void ui_event_btnStart(lv_event_t * e);
lv_obj_t * ui_btnStart;
lv_obj_t * ui_lblButton4;
void ui_event_btnStop(lv_event_t * e);
lv_obj_t * ui_btnStop;
lv_obj_t * ui_lblButton5;
void ui_event_btnAggiorna(lv_event_t * e);
lv_obj_t * ui_btnAggiorna;
lv_obj_t * ui_lblButton3;
void ui_event_Dropdown2(lv_event_t * e);
lv_obj_t * ui_Dropdown2;
lv_obj_t * ui_LabelArtista;
lv_obj_t * ui_LabelCanzone;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label5;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_scrMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrRadio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrRadio_screen_init);
    }
}
void ui_event_pnlMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrRadio, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_scrRadio_screen_init);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnButtonNextClicked(e);
    }
}
void ui_event_scrSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrRadio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrRadio_screen_init);
    }
}
void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrRadio, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrRadio_screen_init);
    }
}
void ui_event_sldVolume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        onVolumeSliderChanged(e);
    }
}
void ui_event_sldBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        onBrightnessSliderChanged(e);
    }
}
void ui_event_ButtonOK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrMain_screen_init);
    }
}
void ui_event_scrRadio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_scrMain_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrSettings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrSettings_screen_init);
    }
}
void ui_event_btnStart(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnButtonStartClicked(e);
    }
}
void ui_event_btnStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnButtonStopClicked(e);
    }
}
void ui_event_btnAggiorna(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        OnButtonAggiornaClicked(e);
    }
}
void ui_event_Dropdown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        onChangeRadioURL(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrMain_screen_init();
    ui_scrSettings_screen_init();
    ui_scrRadio_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrMain);
}
