// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void OnButtonNextClicked(lv_event_t * e);
void onVolumeSliderChanged(lv_event_t * e);
void onBrightnessSliderChanged(lv_event_t * e);
void OnButtonStartClicked(lv_event_t * e);
void OnButtonStopClicked(lv_event_t * e);
void OnButtonAggiornaClicked(lv_event_t * e);
void onChangeRadioURL(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
