// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_scrRadio_screen_init(void)
{
    ui_scrRadio = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrRadio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnStart = lv_btn_create(ui_scrRadio);
    lv_obj_set_width(ui_btnStart, 68);
    lv_obj_set_height(ui_btnStart, 40);
    lv_obj_set_x(ui_btnStart, -309);
    lv_obj_set_y(ui_btnStart, 254);
    lv_obj_set_align(ui_btnStart, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnStart, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnStart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblButton4 = lv_label_create(ui_btnStart);
    lv_obj_set_width(ui_lblButton4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblButton4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblButton4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblButton4, "Start");

    ui_btnStop = lv_btn_create(ui_scrRadio);
    lv_obj_set_width(ui_btnStop, 68);
    lv_obj_set_height(ui_btnStop, 40);
    lv_obj_set_x(ui_btnStop, -228);
    lv_obj_set_y(ui_btnStop, 253);
    lv_obj_set_align(ui_btnStop, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnStop, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblButton5 = lv_label_create(ui_btnStop);
    lv_obj_set_width(ui_lblButton5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblButton5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblButton5, -1);
    lv_obj_set_y(ui_lblButton5, 1);
    lv_obj_set_align(ui_lblButton5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblButton5, "Stop");

    ui_btnAggiorna = lv_btn_create(ui_scrRadio);
    lv_obj_set_width(ui_btnAggiorna, 75);
    lv_obj_set_height(ui_btnAggiorna, 40);
    lv_obj_set_x(ui_btnAggiorna, -5);
    lv_obj_set_y(ui_btnAggiorna, 19);
    lv_obj_set_align(ui_btnAggiorna, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnAggiorna, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnAggiorna, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblButton3 = lv_label_create(ui_btnAggiorna);
    lv_obj_set_width(ui_lblButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblButton3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblButton3, -1);
    lv_obj_set_y(ui_lblButton3, 1);
    lv_obj_set_align(ui_lblButton3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblButton3, "Aggiorna");

    ui_Dropdown2 = lv_dropdown_create(ui_scrRadio);
    lv_dropdown_set_options(ui_Dropdown2, "Virgin Radio");
    lv_obj_set_width(ui_Dropdown2, lv_pct(80));
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 5);
    lv_obj_set_y(ui_Dropdown2, -121);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_LabelArtista = lv_label_create(ui_scrRadio);
    lv_obj_set_width(ui_LabelArtista, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArtista, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelArtista, -36);
    lv_obj_set_y(ui_LabelArtista, -50);
    lv_obj_set_align(ui_LabelArtista, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArtista, "");

    ui_LabelCanzone = lv_label_create(ui_scrRadio);
    lv_obj_set_width(ui_LabelCanzone, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCanzone, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCanzone, -34);
    lv_obj_set_y(ui_LabelCanzone, 10);
    lv_obj_set_align(ui_LabelCanzone, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCanzone, "");

    ui_Label3 = lv_label_create(ui_scrRadio);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -200);
    lv_obj_set_y(ui_Label3, -50);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Artista");

    ui_Label5 = lv_label_create(ui_scrRadio);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -200);
    lv_obj_set_y(ui_Label5, 10);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Canzone");

    lv_obj_add_event_cb(ui_btnStart, ui_event_btnStart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnStop, ui_event_btnStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnAggiorna, ui_event_btnAggiorna, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrRadio, ui_event_scrRadio, LV_EVENT_ALL, NULL);

}
